version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: user-service-db
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
